version: '3.3'

services:

  # MySQL DBs
  db_1:
    image: mysql:5.7.28
    container_name: 1_manage_account_db
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password --max-allowed-packet=300M
    environment:
      MYSQL_DATABASE: 1_manage_account
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - 3306:3306

  db_2:
    image: mysql:5.7.28
    container_name: 2_expose_entities_db
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password --max-allowed-packet=300M
    environment:
      MYSQL_DATABASE: 2_expose_entities
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - 3307:3306

  1_manage_account:
    build: ../docker-images/1_manage_account/
    container_name: manage_account
    restart: on-failure
    environment:
        spring_profiles_active: docker
    ports:
      - 8081:8081
    depends_on:
      - db_1

  2_expose_entities:
    build: ../docker-images/2_expose_entities/
    container_name: expose_entities
    restart: on-failure
    environment:
        spring_profiles_active: docker
    ports:
      - 8080:8080
    depends_on:
      - db_2
