version: '3.3'

services:

  # MySQL DBs
  db_1:
    image: mysql:5.7.28
    container_name: 1_manage_account_db
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password --max-allowed-packet=300M
    environment:
      MYSQL_DATABASE: 1_manage_account
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - 3306:3306

  db_2:
    image: mysql:5.7.28
    container_name: 2_expose_entities_db
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password --max-allowed-packet=300M
    environment:
      MYSQL_DATABASE: 2_expose_entities
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - 3307:3307
